import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";

import "./globals.css";

import { ReactQueryClientProvider } from "@/components/react-query-client-provider";

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body
          className={`${nunitoSans.className} antialiased bg-neutral-20 !dark`}
        >
          {children}
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
